# Default values are set here (just in the pure Python way).

# __all__ = []

SCALES = 3
SIGMA = 1.6
DSAMP_INTVL = 2
INTERP_STEPS = 5
CONTR_THR = 0.04
STAB_THR = 10
ORI_HIST_SEARCH_SIGMA_FCTR = 1.5
ORI_HIST_SEARCH_RADIUS = 4.5  # 3 * ORI_HIST_SEARCH_SIGMA_FCTR
ORI_PEAK_RATIO = 0.8
ORI_HIST_BINS = 36
ORI_HIST_SMOOTH_STEPS = 2
DESCR_HIST_AREAS = 4
DESCR_HIST_BINS = 8
DESCR_MAG_THR = 0.2
DESCR_TO_INT_FCTR = 512.0
OUT_PATH = "./test_out/"
