# Default values are set here (just in the pure Python way).

# __all__ = []

SIGMA = 1.6
DSAMP_INTVL = 2
INTERP_NITER = 5
CONTR_THR = 0.03
STAB_THR = 10
ORI_HIST_SEARCH_SIGMA_FCTR = 1.5
ORI_HIST_SEARCH_RADIUS = 4.5  # 3 * ORI_HIST_SEARCH_SIGMA_FCTR
ORI_PEAK_RATIO = 0.8
ORI_HIST_BINS = 36
DESCR_MAG_THR = 0.2
